server:
  port: 8081

spring:
  application:
    name: auth-service
  config:
    import: "optional:configserver:"
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: kidpass
      username: admin
      password: admin
      authentication-database: admin

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

#management:
#  tracing:
#    sampling:
#      probability: 1.0
#  zipkin:
#    tracing:
#      endpoint: http://localhost:9411/api/v2/spans

jwt:
  secret: aVeryLongAndSecureSecretKeyThatIsAtLeast512BitsLongAndShouldBeUsedForHS512
  expiration: 86400000
