server:
  port: 8089

spring:
  config:
    import: "optional:configserver:"
  application:
    name: authorization-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: kidpass
      username: kidpass
      password: admin
      authentication-database: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

jwt:
  secret: mysecret
  expiration: 86400000