server:
  port: 9090

spring:
  config:
    import: "optional:configserver:"
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: profile-service
          uri: lb://profile-service
          predicates:
            - Path=/api/profiles/**
        - id: activity-service
          uri: lb://activity-service
          predicates:
            - Path=/api/activities/**
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/api/bookings/**
        - id: provider-service
          uri: lb://provider-service
          predicates:
            - Path=/api/providers/**
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/api/students/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
        - id: authorization-service
          uri: lb://authorization-service
          predicates:
            - Path=/api/authorizations/**
        - id: qr-service
          uri: lb://qr-service
          predicates:
            - Path=/api/qrs/**
        - id: security-scanner-service
          uri: lb://security-scanner-service
          predicates:
            - Path=/api/security-scanners/**
        - id: reporting-service
          uri: lb://reporting-service
          predicates:
            - Path=/api/reports/**
      loadbalancer:
        retry:
          enabled: true

eureka:
  client:
    register-with-eureka: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

#management:
#  tracing:
#    sampling:
#      probability: 1.0
#  zipkin:
#    tracing:
#      endpoint: http://zipkin:9411/api/v2/spans

jwt:
  secret: mysecret
