server:
  port: 8087

spring:
  application:
    name: student-service
  config:
    import: "optional:configserver:"
  data:
    mongodb:
      host: localhost
      port: 27017
      database: kidpass
      username: kidpass
      password: admin
      authentication-database: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans