server:
  port: 8092

spring:
  application:
    name: reporting-service
  data:
    mongodb:
      host: mongodb

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans