server:
  port: 8082

spring:
  config:
    import: "optional:configserver:http://config-server:8888"
  application:
    name: user-service
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans