version: '3.8'

services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.0
    ports:
      - "5044:5044"
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline/
    networks:
      - kidpass-network
networks:
  kidpass-network:
    driver: bridge

#    docker run -d --name logstash \
#    --network kidpass-network \
#    --restart always \
#    -p 5044:5044 \
#    -v "./pipeline:/usr/share/logstash/pipeline/" \
#    docker.elastic.co/logstash/logstash:7.17.0