server:
  port: 8888

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///config-repo
          default-label: main

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
